services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5449:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DroneRecordDb
    container_name: DroneDb
    volumes:
      - postgres:/var/lib/postgresql/data
