default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: 'postgres'
  password: 'root'
  timeout: 5000

development:
  <<: *default
  database: drone-db-development

test:
  <<: *default
  database: drone-db-test

production:
  <<: *default
  database: drone-db-production
